### ISSUE TITLE
SetRange issue

### ISSUE THREAD

**Issue by wakiboi** [sparkfun/SparkFun_ADXL313_Arduino_Library#7]
The 1.0.2 version of the library always results in a compilation error. Therefore, we opted to use the 1.0.0 instead. Everything seems to be functioning well, but when we change the range to 0.5G ("ADXL313_RANGE_05_G"), it gives the same result as the 1G, which is 512 LSB/g (should be 1024 LSB/g based on the ADXL313's datasheet). Do you have a fix for this issue yet? Thank you.

**Comment by lewispg228** [comment]
Thank you for bringing this to our attention. The compilation error has been fixed with this [this commit](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/commit/32bc8376500c4d0daf24bee45ebe6ef864514c24) and release v1.0.3.

However, the range issue you describe is new to us. There was an [issue](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/issues/1) with `getRange()`, but the `setRange()` seems to be working on my hardware. 

How have you been verifying the range settings? 

If you were using getRange(), then this would have been misleading before (but it is now fixed to correctly return the actual range setting).

Also, to verify the range, I usually look at the Z readings. When it's sitting flat on my desk, it should read the following for each range setting. Note, the +/-0.5G is maxed out at flat (because you are at 1G, so double it's positive range limit).

+/- 0.5g = 512

+/- 1g = 512

+/- 2g = ~250

+/- 4g = ~125

Note, with scrolling data, I try flipping it upside down, and then verify that the readings go to the negative limit equivalent.

And with the +/-0.5g range, you should notice it "max out at 512" somewhere partially through the rotation.

Also note, I added in a print out of the actual range setting into example 2, to help show/remember what setting your at.

![image](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/assets/601236/5318fa0e-2a94-4b2c-a7c1-2e06fd980f42)


Hope this helps!

Let us know and thanks,
Pete

**Comment by lewispg228** [comment]
Closing this issue for now. Please feel free to re-open if necessary. Thanks!
