### ISSUE TITLE
0.5g Range Value maxed at 512

### ISSUE THREAD

**Issue by Atomb6** [sparkfun/SparkFun_ADXL313_Arduino_Library#8]
When setting the range using "myAdxl.setRange(ADXL313_RANGE_05_G);" the max range is only 512 the same with 1g.  The libary version used is 1.0.2 and there were no errors in compiling just the 0.5g range value issue. Is there a fix for this issue? Thank you for your time and consideration.

**Comment by lewispg228** [comment]
Hi There @Atomb6 ,
The compilation issue has been fixed in the latest release (v1.0.3). Please update and give this a try. 

About the resolution, The resolution from the sensor is by default set to 10-bit, so this is a range of 0-1023. And this is for both a positive and negative limit of the range setting. So that would be -512 to +512. Is this what you are experiencing?

You can adjust the resolution using `myAdxl.setFullResBit(1);` ([see library function here](https://github.com/sparkfun/SparkFun_ADXL313_Arduino_Library/issues/7#issuecomment-1930769250)) but know that this plays together with range, scale factor, and data rates. More about this in the [datasheet](https://cdn.sparkfun.com/assets/1/d/a/8/8/ADXL313_datasheet.pdf), pages 3 and 24. 

Hope this helps and let us know how it goes!
Pete
